# actions document: https://docs.github.com/en/actions/using-jobs/using-jobs-in-a-workflow
# official actions: https://github.com/actions

name: 'Deployment lemonied.github.io'

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  SITE_URL: https://www.lemonied.cn

jobs:
  deployment:
    runs-on: ubuntu-latest
    strategy: 
      matrix:
        node-version: [16]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Build
        run: |
          sh ./mtime.sh
          npm install
          npm run pkgs:build
          npm run build
          npm run export
      - name: Push To Branch Blog
        run: |
          git config --global user.email 447334358@qq.com
          git config --global user.name action-bot
          cd ./out
          git init
          git branch -m blog
          git add .
          git commit -m "Deploy by Actions"
          git remote add origin https://${{secrets.TOKEN}}@github.com/lemonied/lemonied.github.io.git
          git push -u -f origin blog:blog
