# actions document: https://docs.github.com/en/actions/using-jobs/using-jobs-in-a-workflow
# official actions: https://github.com/actions

name: 'Deployment lemonied.github.io'

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  NEXT_TELEMETRY_DISABLED: 1
  SITE_URL: ${{ vars.SITE_URL }}
  BASE_PATH: /

jobs:
  deployment:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: [16]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: master
          fetch-depth: 0
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Build
        run: |
          yarn install
          yarn run pkgs:build
          yarn run mtime
          yarn run build
          yarn run export
      - name: Push To Repository
        run: |
          git config --global user.email ${{ vars.USER_EMAIL }}
          git config --global user.name action-bot
          cd ./out
          git init
          git branch -m blog
          git add .
          git commit -m "Deploy by Actions"
          git remote add origin https://${{secrets.TOKEN}}@github.com/${{ vars.CODE_GITHUB_REPOSITORY }}
          git push -u -f origin HEAD:${{ vars.CODE_GITHUB_BRANCH }}
