name: 'Deploy lemonied.github.io'

# **What it does**: Renders the content of every page and check all internal links.
# **Why we have it**: To make sure all links connect correctly.
# **Who does it impact**: Docs content.

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  deployment:
    runs-on: ubuntu-latest
    strategy: 
      matrix:
        node-version: [16]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: |
          npm install && npm run build && npm run export
      - name: Setup Git Config
        run: |
          git config --global user.email 447334358@qq.com
          git config --global user.name action-bot
          cd ./out
          git init
          git branch -m blog
          git add .
          git commit -m "Deploy by Actions"
          git remote add origin https://${{secrets.TOKEN}}@github.com/lemonied/lemonied.github.io.git
          git push -u -f origin blog:blog
